### PR TITLE
Vite build system

### PR DESCRIPTION
**Pull request by steel97**
This PR made to simplify build system, remove eslint warnings and also remove packages which contains vulnerabilities reported by npm during install.

What has been done:
- old build system replaced with **vite** (also removed peerDependencies and outdated rollup plugins)
- moved eslint config from **package.json** to **.eslintrc.cjs**
- **floss** replaced with **vitest**
- updated example code in readme to match new asset loading API
- formatted all sources to eliminate eslint warnings
- replaced **yarn** with **npm** in github actions

My vue3-pixi-tilemap example updated to use this branch: https://steel97.github.io/vue3-pixi-tilemap/

### CODE REVIEW

**Comment by steel97** [comment]
Yes I have permissions to merge it, thanks!

**Comment by YunYouJun** [comment]
I clone this repo, and `npm run start`, but get `PIXI.CanvasRenderer.registerPlugin is not a function`.

Can you start this project?

**Comment by steel97** [comment]
@YunYouJun rpgmaker example is not yet updated. You may try basic example (navigate to basic.html after npm run start)
изображение

**Comment by YunYouJun** [comment]
I have an idea, I think we can build a demo based on vite directly by ts, so when `npm run start`, no need to build before it.

**Comment by YunYouJun** [comment]
> yes we can do that, but in this case examples won't run without vite (currently examples can be launched standalone)

We can write a yml for github-action. Deploy it in `gh-pages` branch or build and preview by vercel/netlify/cloudflare pages.

**Pull request merged**
